### ISSUE TITLE
It's make a mistake : segmentation fault,When run my project on linux，the project used ActiveMQ‘s file and lib

### ISSUE THREAD

**Issue by AthonyLi** [VladRoma/gpsvp#161]
When I in the times of my program runs a wrong: segmentation fault, caused by the `_int_malloc()`; but in my program did not use `malloc`, I only used the ActiveMQ rely on some `dynamic libraries`, and inside it some `.h` file; this problem very troubled me, because I could not find any errors in the place where, because I even I program main have no access to, the fault should be in the dynamic library or the ActiveMQ global variables, however.    Note: the development environment is` [linux]` + `[eclipse for c/c++ ]`. I hope someone can help me. 
   @leomeyer @VladRoma @all

**Comment by AthonyLi** [comment]
I use GDB tool to debug the program,and generate a core file,and then,use `gdb xx.out core.xx` order to debug,this operation produce error info,I find the error occured in my xx.so ( this xx.so generated by my code ): just define some `const std::string` variable,I'm not understand.
@htchepannou @Nigel Schuster @Greg Maslowski @Seiji Sogabe

**Comment by leomeyer** [comment]
Sorry, without code it's probably impossible to help you.
As for segmentation faults in C++, these can be tricky beasts. Creating a std::string instance probably involves a malloc() call; if this fails you likely have a heap corruption somewhere caused by dereferencing an invalid pointer, use-after-free, double free or so. If this is in your own shared library code I highly suspect that you have a bug somewhere; I don't really know the ActiveMQ library but I wouldn't start my search there.
The bad thing is that the code that throws the error is not necessarily the code that causes the error. In such a case you can try valgrind to find the offending code's location. If this doesn't help try to remove code until the bug disappears, then try to reproduce it.
Some hints: Use references instead of pointers wherever possible. Do not return pointers to local variables declared in functions (take care with nested structures). If you allocate memory, make it clear who owns it and who has the responsibility to free it. Use smart pointers where possible (std::unique_ptr is best, std::shared_ptr might be useful, too). Seemingly innocent variable declarations can involve a lot of magic which may fail in unexpected ways.
This is the stony way of programming in C++, and there is no way around it. On the other hand, eliminating such a bug will teach you a lot and give you immense satisfaction. Have fun :-)
